version: "2"
services:
  web:
    build: ./nginx
    ports:
      - "8000:8000"
      - "80:80"
    depends_on:
      - backend
      - print
    networks:
      - back-tier
  print:
    build: ./print
    networks:
      back-tier:
        aliases:
          - "print"
